"""Generate a 5x7 bitmap font as C source.

Hand-encoding a font is 96 glyphs of hex that a reader cannot check and an
author gets subtly wrong - a bad pixel in a rarely-used character survives
until somebody types it. Rendering from a real typeface and committing the
result means the source of truth is a font file and this script, both of which
can be re-run and diffed.

Committed as generated source rather than built at compile time: the firmware
build should not depend on PIL being installed, and a font that changes only
when somebody deliberately regenerates it is one fewer thing that can drift.

Usage: python3 tools/make_font.py > src/font.c
"""

import sys

from PIL import Image, ImageDraw, ImageFont

WIDTH = 6
HEIGHT = 8
FIRST = 0x20
LAST = 0x7E


# A few glyphs no scalable face renders legibly in six pixels. Their diagonals
# fall below any useful threshold and come out as solid blocks - an "M" that is
# indistinguishable from a filled rectangle is worse than one drawn by hand.
#
# Three exceptions, each checkable by eye, rather than hand-entering all 95 and
# hoping. Rows top to bottom, six wide.
OVERRIDES = {
    "A": ["..##..",
          ".#..#.",
          "#....#",
          "#....#",
          "######",
          "#....#",
          "#....#",
          "......"],
    "M": ["#....#",
          "##..##",
          "#.##.#",
          "#....#",
          "#....#",
          "#....#",
          "#....#",
          "......"],
    "W": ["#....#",
          "#....#",
          "#....#",
          "#....#",
          "#.##.#",
          "##..##",
          "#....#",
          "......"],
}

# Liberation Mono at 10 px, thresholded at 96, was the clearest of the faces and
# sizes tried for a 6x8 cell - and 6 px is what the badge already assumes:
# prefs.py bounds its display text at 21 characters, which is 128 pixels wide
# divided by six.
FONT_SIZE = 10
THRESHOLD = 96
Y_OFFSET = -1


def find_font():
    candidates = [
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, FONT_SIZE), path
        except OSError:
            continue
    return ImageFont.load_default(), "PIL default"


def glyph(font, character):
    """One character as WIDTH columns of HEIGHT bits, LSB at the top."""
    if character in OVERRIDES:
        rows = OVERRIDES[character]
        return [
            sum(1 << y for y in range(HEIGHT) if rows[y][x] == "#")
            for x in range(WIDTH)
        ]

    image = Image.new("L", (WIDTH + 6, HEIGHT + 6), 0)
    draw = ImageDraw.Draw(image)
    # Rendered into a larger box and then measured, because a small face's own
    # origin is not where a 6x8 cell wants it.
    draw.text((0, Y_OFFSET), character, font=font, fill=255)

    pixels = image.load()
    columns = []
    for x in range(WIDTH):
        bits = 0
        for y in range(HEIGHT):
            if pixels[x + 1, y + 1] > THRESHOLD:
                bits |= 1 << y
        columns.append(bits)
    return columns


def main():
    font, source = find_font()

    out = sys.stdout.write
    out("/* Generated by tools/make_font.py - do not edit by hand.\n")
    out(" *\n")
    out(" * A %dx%d font, %d glyphs from 0x%02X to 0x%02X, one byte per column\n"
        % (WIDTH, HEIGHT, LAST - FIRST + 1, FIRST, LAST))
    out(" * with the least significant bit at the top - which is the order the\n")
    out(" * SSD1306 wants, so a glyph is copied into the framebuffer rather than\n")
    out(" * transposed into it.\n")
    out(" *\n")
    out(" * Rendered from %s. Generated rather than hand-entered: 95 glyphs of\n"
        % source)
    out(" * hex is a lot of places for a wrong pixel to hide until somebody\n")
    out(" * types the character it belongs to.\n")
    out(" */\n\n")
    out('#include "font.h"\n\n')
    out("const uint8_t FONT_6X8[FONT_GLYPHS][FONT_WIDTH] = {\n")

    for code in range(FIRST, LAST + 1):
        character = chr(code)
        columns = glyph(font, character)
        shown = character if character not in ('\\', '*', '/') else "0x%02X" % code
        out("    {%s},  /* %s */\n"
            % (", ".join("0x%02X" % c for c in columns), shown))

    out("};\n")


if __name__ == "__main__":
    main()
