"""Bake the X11 6x9 bitmap font into a C glyph table.

Three typefaces were tried before this one. Liberation Mono and DejaVu Sans Mono
had to be rendered grey and thresholded, which at six pixels turns thin
diagonals into nothing and thick ones into blocks - the M came out
indistinguishable from a filled rectangle, and three glyphs had to be redrawn by
hand to be legible at all. Departure Mono is a real pixel font and looks
excellent, but only at its native 11 px, which is too tall for a 32-pixel panel.

The X11 misc fonts are hand-drawn on exactly this kind of grid. 6x9 has a proper
crossbar on the A, a real V in the M and W, and true descenders - no threshold
involved anywhere, because every pixel is where somebody put it.

Nine rows, drawn at an eight-pixel pitch, so four lines still fit. Descenders
overhang into the blank top row of the line below; the only glyphs using that
row are $%?{}, none of which appear in a filename. The bottom line's descenders
clip against the edge of the panel by one pixel, which is the price of the
fourth row.

Columns are 16-bit. Nine rows do not fit in a byte, and the previous attempt at
a taller font truncated silently - 382 became 126 - which would have shipped a
corrupted table rather than an obviously wrong one.

Usage: python3 tools/make_font.py > src/font.c
"""

import sys

sys.path.insert(0, "tools")
import pcf  # noqa: E402

SOURCE = "/usr/share/fonts/X11/misc/6x9-ISO8859-1.pcf.gz"
FIRST = 0x20
LAST = 0x7E


def main():
    bitmaps, metrics, encodings = pcf.load(SOURCE)

    width = height = 0
    glyphs = {}
    for code in range(FIRST, LAST + 1):
        index = encodings.get(code)
        if index is None:
            glyphs[code] = None
            continue
        rows, _ = pcf.glyph(bitmaps, metrics, index)
        glyphs[code] = rows
        height = max(height, len(rows))
        width = max(width, len(rows[0]) if rows else 0)

    out = sys.stdout.write
    out("/* Generated by tools/make_font.py - do not edit by hand.\n")
    out(" *\n")
    out(" * The X11 misc 6x9 bitmap font: hand-drawn on this exact grid, so there\n")
    out(" * is no rasterisation or threshold anywhere and every pixel is where\n")
    out(" * somebody put it. %d glyphs, 0x%02X to 0x%02X, in a %dx%d cell.\n"
        % (LAST - FIRST + 1, FIRST, LAST, width, height))
    out(" *\n")
    out(" * One 16-bit word per column, least significant bit at the top - the\n")
    out(" * order the SSD1306 stores a page, so drawing is a copy rather than a\n")
    out(" * transpose. Sixteen bits because nine rows do not fit in eight, and a\n")
    out(" * previous taller font truncated silently rather than failing.\n")
    out(" *\n")
    out(" * Source: %s\n" % SOURCE)
    out(" */\n\n")
    out('#include "font.h"\n\n')
    out("const uint16_t FONT_GLYPH[FONT_GLYPHS][FONT_WIDTH] = {\n")

    for code in range(FIRST, LAST + 1):
        rows = glyphs[code]
        columns = []
        for x in range(width):
            bits = 0
            if rows is not None:
                for y in range(min(height, len(rows))):
                    if x < len(rows[y]) and rows[y][x]:
                        bits |= 1 << y
            columns.append(bits)
        character = chr(code)
        label = character if character not in ("\\", "*", "/") else "0x%02X" % code
        out("    {%s},  /* %s */\n"
            % (", ".join("0x%04X" % c for c in columns), label))

    out("};\n")
    sys.stderr.write("cell %dx%d, %d glyphs from %s\n"
                     % (width, height, LAST - FIRST + 1, SOURCE))


if __name__ == "__main__":
    main()
